export interface CalendarAvailability {
  id?: number; // Optional since it's auto-generated by backend
  date: string;  // Format: 'YYYY-MM-DD' to match LocalDate
  isAvailable: boolean;
  timeSlots: TimeSlot[];
}

export interface TimeSlot {
  id?: number; // Optional for backend operations
  time: string;   // Format: 'HH:MM AM/PM' or 'HH:mm' depending on your needs
  isAvailable: boolean;
}

// Additional types for better type safety
export interface SaveResult {
  success: boolean;
  date: string;
  result?: CalendarAvailability;
  error?: any;
} 